name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Set Release Version
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    - name: Get Release version
      run: echo $RELEASE_VERSION

    - name: Update Git Identity
      run: git config --global user.name '@vreshch' && git config --global user.email 'vreshch@gmail.com' && git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Setup npmrc File
      run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Publish to NPM
      run: node set-version $RELEASE_VERSION && npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
